# Generated by Django 5.1.1 on 2024-09-18 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('public_location', models.CharField(max_length=255)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('image', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('organizer_name', models.CharField(max_length=255)),
                ('organizer_avatar', models.CharField(max_length=255)),
                ('organizer_contact', models.CharField(max_length=255)),
                ('participants', models.IntegerField()),
                ('tags', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_moderator', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('age_restriction', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
